### ISSUE TITLE
Pfp's are on the messages 

### ISSUE THREAD

**Issue by squabblez** [rauenzi/Nox#10]
I don't know if its a setting I have on wrong or if its a bug, but if it is a bug please fix asap  

![image](https://user-images.githubusercontent.com/35447860/61604535-e9e38600-ac0f-11e9-9d34-ed1ab9a3bb8c.png)

**Comment by Elisniper** [comment]
You can put  the code below in your "custom css" as a temp fix till it gets fixed!

/* TEMP FIX (for broken avatars) STABLE */
.avatar-17mtNa {
    position: relative;
}

**Comment by squabblez** [comment]
Just making sure, do I just copy and paste "/TEMP FIX (for broken avatars) STABLE/
.avatar-17mtNa {
position: relative;
}" into custom css?

**Comment by Elisniper** [comment]
you dont have to coppy the part that is in the "/* comment */" just form the .avatar and next.

**Comment by squabblez** [comment]
alright, thank you so much! :)

**Comment by zerebos** [comment]
This should now be fixed.
