### ISSUE TITLE
Profile image offsets wrong

### ISSUE THREAD

**Issue by itsTyrion** [rauenzi/Nox#12]
![image](https://user-images.githubusercontent.com/17730120/62805032-17c13980-baef-11e9-9057-2dd97e20aae1.png)
I just installed BBD on my Manjaro installation, copied all BBD stuff over from the Windoze setup and found the offsets to be seriously wrong. 

Tell me what to provide that smells like a log file and I'll provide it. (ClearVision is working btw!)
I tried disabling the plugins, problem persists. 

I also tried redownloading, which, of course, due to the "import", didn't change anything. 

RadialStatus doesn't appear to be working either, which makes me wonder wether Discord changed something?

**Comment by itsTyrion** [comment]
![image](https://user-images.githubusercontent.com/17730120/62805899-9e771600-baf1-11e9-8ed7-2f9450828a7d.png)
full screenshot with some blur for privacy/cringe reasons 🙃

**Comment by FroztySeven** [comment]
This has already been reported many times on the theme's discord server by the community. 
People have already made tempfixes for this on the server, until there's a new theme update to fix that.
This is a theme re-lated bug. It isn't caused by your plugins.

**Comment by FroztySeven** [comment]
I would suggest you to either wait until the theme gets updated, or rely on tempfixes right now

**Comment by itsTyrion** [comment]
> This has already been reported many times on the theme's discord server by the community.
> People have already made tempfixes for this on the server, until there's a new theme update to fix that.
> This is a theme re-lated bug. It isn't caused by your plugins.

Ah. So there's a fix on the Nox Discord guild? 
I didn't see an open GitHub issue ̶f̶̶o̶̶r̶̶ ̶̶t̶̶h̶̶a̶̶t̶̶,̶̶ ̶̶t̶̶h̶̶a̶̶t̶'̶s̶̶ ̶̶w̶̶h̶̶y̶̶ ̶̶i̶̶ ̶̶o̶̶p̶̶e̶̶n̶̶e̶̶d̶̶ ̶̶o̶̶n̶̶e̶  for that because I'm just dumb and tired xD

**Comment by FroztySeven** [comment]
> > This has already been reported many times on the theme's discord server by the community.
> > People have already made tempfixes for this on the server, until there's a new theme update to fix that.
> > This is a theme re-lated bug. It isn't caused by your plugins.
> 
> Ah. So there's a fix on the Nox Discord guild?
> I didn't see an open GitHub issue for that, that's why I opened one

Yes

**Comment by itsTyrion** [comment]
Duplicate of #10 
Duplicate of #11

**Comment by zerebos** [comment]
This should now be fixed.
