### ISSUE TITLE
Unread channel's aren't white

### ISSUE THREAD

**Issue by FichteFoll** [rauenzi/Nox#13]
With the latest discord update, unread channels don't have white text anymore and just show the indicator on the side.

![2019-09-11_17-15-53](https://user-images.githubusercontent.com/931051/64710222-d5a56200-d4b7-11e9-9dc6-9cbcd9294d17.png)

There need to be new selectors for `.modeUnread-1zpFdA`, probably.

**Comment by FroztySeven** [comment]
Tempfix already available on the discord server

**Comment by zerebos** [comment]
This should now be fixed.
