### ISSUE TITLE
Theme no longer works properly with discord 0.0.305

### ISSUE THREAD

**Issue by GrayGray72** [rauenzi/Nox#2]
The theme's background is the default background on the activity screen. Also the left side bar is no longer the correct color too. 

Activity Page Screen Shot:
![f6fd6d63ff58390104cb09be112d6e34](https://user-images.githubusercontent.com/49378176/55691168-3f4d9d00-5969-11e9-99e0-4ddfac151b61.png)

Left Side Bar Screen Shot:
![4f52930af954dbbdde6e800e213d44da](https://user-images.githubusercontent.com/49378176/55691173-53919a00-5969-11e9-8e8c-90387902728e.png)

**Comment by zerebos** [comment]
Fixed with 1.0.2
