### ISSUE TITLE
Powercord support

### ISSUE THREAD

**Issue by MostHated** [rauenzi/Nox#24]
Hey there,
   I use the [Powercord framework](https://powercord.dev/) for Discord but wanted to use this theme, so I thought I would give it a go by just comparing this to some other themes I know worked for Powercord. The main thing that jumped out was it requires a file in the root folder called "powercord_manifest.json", so I made one and filled it out with the following:

```json
{
	"name": "NOX",
	"description": "NOX",
	"author": "NOX",
	"version": "1.0.0",
	"license": "NOX",
	"theme": "release/Nox.theme.css"
}

```

Surprisingly, it mostly worked. (blocked out a few things in respect to their privacy)

<details>
<summary>Screenshot</summary>

![](https://i.imgur.com/3adMDv0.png)

</details>

That said, it looks like it may not take much for it to be fully supported so I was wondering if it might be at all possible to consider offering official support for Powercord?

Thanks,
-MH

**Comment by DetermineAbsurd** [comment]
Made a PR for this. Don't worry, I totally didn't just accidentally make a PR on my own forked repo because I'm not sleep deprived 😅

**Comment by zerebos** [comment]
This theme is currently meant for BetterDiscord and uses a lot selectors that are provided by BD itself. At this time, I do not wish to make it publicly available for Powercord.

**Comment by MostHated** [comment]
No worries, I can understand and respect the decision.
