### ISSUE TITLE
i am lagging when i turn this theme on.

### ISSUE THREAD

**Issue by rhys19** [rauenzi/Nox#3]
downloaded the theme, enabled then i exited out to start seeing lag like discord was in 0.1 Beta. but when i turn the theme off it works perfect! any idea what's causing this?

**Comment by zerebos** [comment]
This theme changes a lot of things, I would suggest turning on Hardware Acceleration in Discord.

**Comment by rhys19** [comment]
Ah, that fixed it thank you!
