### ISSUE TITLE
Small Server Icons and other bugs. But the Folder are the same as discord. [ More Details If you clicked this. ]

### ISSUE THREAD

**Issue by zenzensee** [rauenzi/Nox#33]
Small Server images but the Folder are the same as discord.
[ More Details ]
|
↓
![image](https://user-images.githubusercontent.com/82157577/114218644-41a1c200-999c-11eb-8795-93a69370ac22.png)
![image](https://user-images.githubusercontent.com/82157577/114219504-4f0b7c00-999d-11eb-82a5-c2871d91b966.png)
![image](https://user-images.githubusercontent.com/82157577/114220808-0a80e000-999f-11eb-93c1-f152658ecf77.png)
![image](https://user-images.githubusercontent.com/82157577/114222768-8e3bcc00-99a1-11eb-9e33-bfbfbdf349b2.png)

**Comment by froyo4u** [comment]
I made a fix for it, if you're in the Discord here's the link to it: [Nox 2: Electric Boogaloo](https://discord.com/channels/295022867865665548/295022867865665548/826794979594076180)

**Comment by Nikdan92** [comment]
Maybe I'm doing something wrong, but your link doesn't work
![image](https://user-images.githubusercontent.com/82333085/114314954-885efb80-9b05-11eb-9b95-d21c94d8d300.png)



> I made a fix for it, if you're in the Discord here's the link to it: [Nox 2: Electric Boogaloo](https://discord.com/channels/295022867865665548/295022867865665548/826794979594076180)

**Comment by zenzensee** [comment]
Where is it? when i clicked the link, it directs me to my discord. I like
the theme so much. Please fix it.

**Comment by zenzensee** [comment]
Where is it? when i clicked the link, it directs me to my discord. I like
the theme so much. Please fix it.

I'll spam this until you fix.

>

**Comment by zenzensee** [comment]
Where is it? when i clicked the link, it directs me to my discord. I
like the theme so much. Please fix it.

I'll spam this until you fix.

**Comment by zenzensee** [comment]
![image](https://user-images.githubusercontent.com/82157577/114388528-5feb0600-9bc6-11eb-8b5c-f9a89717a748.png)
not working.

**Comment by zenzensee** [comment]
> I made a fix for it, if you're in the Discord here's the link to it: [Nox 2: Electric Boogaloo](https://discord.com/channels/295022867865665548/295022867865665548/826794979594076180)

**Comment by vs0usa** [comment]
You have to [join the support server](https://discord.com/invite/vzKhKTV) to be able to click on the fix link

**Comment by zenzensee** [comment]
Thanks.
