### ISSUE TITLE
discord boost icon misaligned in dropdown list

### ISSUE THREAD

**Issue by ralsei** [rauenzi/Nox#4]
self-explanatory
on BD 0.3.2/BBD 0.2.17/Nox 1.0.2

![](https://user-images.githubusercontent.com/16062051/59454686-a6138a80-8de0-11e9-9dba-a0664982342b.png)

**Comment by ralsei** [comment]
additionally, when you hover over a user and the icon gets larger, the Boost icon next to them (if present) does not shift right with the text

**Comment by zerebos** [comment]
This should now be fixed.
