### ISSUE TITLE
Broken on latest

### ISSUE THREAD

**Issue by NextdoorPsycho** [rauenzi/Nox#42]
Unfortunately the whole theme is not working as of 04/11/2022. its been broken for some time (on canary and latest) but i assumed i was doing something wrong, however it just seems to be a dead theme as of now

**Comment by tpeterka1** [comment]
There are fixes in the Discord server

**Comment by froyo4u** [comment]
yeah join the discord: https://discord.com/invite/vzKhKTV

**Comment by froyo4u** [comment]
I've been fixing the theme mostly

**Comment by NextdoorPsycho** [comment]
So they are not being updated on the Git? ok. Strange but ok

**Comment by froyo4u** [comment]
The original creator isn't updating the theme right now, so I've been fixing things
