### ISSUE TITLE
Mute and Deafen buttons invisible

### ISSUE THREAD

**Issue by h-exx** [rauenzi/Nox#5]
Mute and Deafen buttons are invisible in newest stable update.
I'm not sure how to reproduce it as it just randomly happened when I started up discord. It's been like this since yesterday.
![image](https://user-images.githubusercontent.com/17961641/59561081-83b58300-9013-11e9-980b-eb62e2f04248.png)

**Comment by magistau** [comment]
Have the same

**Comment by Ceiridge** [comment]
Here's a temporary fix (custom CSS) that I've found on the Nox Discord:
`.container-2Thooq .horizontal-1ae9ci div svg {display:flex;}`
by Јªѵª# 0007

It displays the old discord icons again and thus it should be removed after a proper fix.

**Comment by PseudoProxen** [comment]
Also listed in TempFixes on Discord, but this will display Nox theme icons now. 

https://gist.github.com/PseudoProxen/b9522c4dbde00252646365cac0bd7081

**Comment by zerebos** [comment]
This should now be fixed.
