### ISSUE TITLE
Gap in between home button and first server

### ISSUE THREAD

**Issue by JIENX** [rauenzi/Nox#7]
Has been a problem for over 2 weeks, is still around. Am not able to move a server there as it is just a blank space.

![nox](https://user-images.githubusercontent.com/51894415/59572914-3fab9800-907e-11e9-91aa-76d11a97d373.png)

**Comment by zerebos** [comment]
Are you using BetterDiscord?

**Comment by Jefferderp** [comment]
I'm using BandagedBetterDiscord, and can confirm I've had the same issue for some weeks.

**Comment by wellbrained** [comment]
This is caused by the hidden "Public Server". 

Tempfix for it:
```css
.listItem-2P_4kh:nth-child(3) {
    display: none;
}
```

**Comment by aidenjay345** [comment]
That fix is broken, fixed it by replacing the 3 with a 2

`.listItem-2P_4kh:nth-child(3) {
    display: none;
}`

**Comment by zerebos** [comment]
This should now be fixed.
